"""add retrieval metadata to chat messages

Revision ID: 1e5960d4f1dd
Revises: 7cf008b005d9
Create Date: 2026-01-20 17:24:58.793485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e5960d4f1dd'
down_revision: Union[str, Sequence[str], None] = '7cf008b005d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('retrieval_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Search and retrieval metadata for audit trail'))
    op.add_column('chat_messages', sa.Column('context_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full chunks used for context (audit trail)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'context_chunks')
    op.drop_column('chat_messages', 'retrieval_metadata')
    # ### end Alembic commands ###
