"""add provider_settings table

Revision ID: 221b171a988e
Revises: 1e5960d4f1dd
Create Date: 2026-01-22 06:43:24.663668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221b171a988e'
down_revision: Union[str, Sequence[str], None] = '1e5960d4f1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_settings',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key (always 1 - singleton pattern)'),
    sa.Column('embedding_provider', sa.String(length=50), server_default='openai', nullable=False, comment='Current embedding provider (openai, ollama)'),
    sa.Column('llm_provider', sa.String(length=50), server_default='openai', nullable=False, comment='Current LLM provider (openai, anthropic)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last updated timestamp'),
    sa.CheckConstraint('id = 1', name='settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_settings')
    # ### end Alembic commands ###
