"""initial schema

Revision ID: 608494810fe8
Revises:
Create Date: 2026-01-18 19:49:00.269778

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "608494810fe8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
