"""add chat_messages table

Revision ID: 7cf008b005d9
Revises: ba8b4cfe8902
Create Date: 2026-01-19 13:51:41.188882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cf008b005d9'
down_revision: Union[str, Sequence[str], None] = 'ba8b4cfe8902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user or assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message text content'),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Source citations for assistant messages'),
    sa.Column('llm_provider', sa.String(length=50), nullable=True, comment='LLM provider used (openai, anthropic)'),
    sa.Column('llm_model', sa.String(length=100), nullable=True, comment='Specific model identifier'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Total tokens consumed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
