"""add extraction fields to articles

Revision ID: b7839a12542a
Revises: efc9ad78d9eb
Create Date: 2026-01-19 11:08:13.588632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7839a12542a'
down_revision: Union[str, Sequence[str], None] = 'efc9ad78d9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA-256 hash of content for deduplication'))
    op.add_column('articles', sa.Column('extraction_method', sa.String(length=50), nullable=True, comment='Method used for extraction (trafilatura, pymupdf, etc.)'))
    op.add_column('articles', sa.Column('extraction_error', sa.Text(), nullable=True, comment='Error message if extraction failed'))
    op.add_column('articles', sa.Column('canonical_url', sa.String(length=2048), nullable=True, comment='Final URL after redirects'))
    op.add_column('articles', sa.Column('author', sa.String(length=512), nullable=True, comment='Article author'))
    op.add_column('articles', sa.Column('published_date', sa.DateTime(timezone=True), nullable=True, comment='Publication date (if available)'))
    op.add_column('articles', sa.Column('language', sa.String(length=10), nullable=True, comment="Detected language code (e.g., 'en', 'fr')"))
    op.add_column('articles', sa.Column('word_count', sa.Integer(), nullable=True, comment='Number of words in content'))
    op.add_column('articles', sa.Column('reading_time_minutes', sa.Integer(), nullable=True, comment='Estimated reading time in minutes'))
    op.add_column('articles', sa.Column('extraction_metadata', sa.JSON(), nullable=True, comment='Additional metadata from extraction (keywords, tags, etc.)'))
    op.add_column('articles', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True, comment='When extraction completed successfully'))
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.drop_column('articles', 'extracted_at')
    op.drop_column('articles', 'extraction_metadata')
    op.drop_column('articles', 'reading_time_minutes')
    op.drop_column('articles', 'word_count')
    op.drop_column('articles', 'language')
    op.drop_column('articles', 'published_date')
    op.drop_column('articles', 'author')
    op.drop_column('articles', 'canonical_url')
    op.drop_column('articles', 'extraction_error')
    op.drop_column('articles', 'extraction_method')
    op.drop_column('articles', 'content_hash')
    # ### end Alembic commands ###
