"""add embedding fields to articles

Revision ID: ba8b4cfe8902
Revises: b7839a12542a
Create Date: 2026-01-19 12:47:25.236029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8b4cfe8902'
down_revision: Union[str, Sequence[str], None] = 'b7839a12542a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the embedding_status enum type first
    op.execute("CREATE TYPE embedding_status AS ENUM ('pending', 'processing', 'completed', 'failed')")

    op.add_column('articles', sa.Column('embedding_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='embedding_status', create_constraint=True, create_type=False), server_default='pending', nullable=False, comment='Embedding generation status'))
    op.add_column('articles', sa.Column('chunk_count', sa.Integer(), nullable=True, comment='Number of chunks created during embedding'))
    op.create_index(op.f('ix_articles_embedding_status'), 'articles', ['embedding_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_embedding_status'), table_name='articles')
    op.drop_column('articles', 'chunk_count')
    op.drop_column('articles', 'embedding_status')

    # Drop the embedding_status enum type
    op.execute("DROP TYPE embedding_status")
    # ### end Alembic commands ###
