"""add last_successful_chunk_index to articles

Revision ID: d05c5946b608
Revises: 221b171a988e
Create Date: 2026-01-29 19:39:13.939006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05c5946b608'
down_revision: Union[str, Sequence[str], None] = '221b171a988e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('last_successful_chunk_index', sa.Integer(), nullable=True, comment='Index of last successfully embedded chunk (for resume on failure)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'last_successful_chunk_index')
    # ### end Alembic commands ###
