"""add articles table

Revision ID: efc9ad78d9eb
Revises: f304b02c7230
Create Date: 2026-01-19 10:52:57.062949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc9ad78d9eb'
down_revision: Union[str, Sequence[str], None] = 'f304b02c7230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Parent research session'),
    sa.Column('type', sa.Enum('url', 'file', name='article_type', create_constraint=True), nullable=False, comment='Article source type (url or file)'),
    sa.Column('original_url', sa.String(length=2048), nullable=True, comment='Source URL for url-type articles'),
    sa.Column('original_filename', sa.String(length=255), nullable=True, comment='Original filename for file-type articles'),
    sa.Column('storage_path', sa.String(length=512), nullable=True, comment='Filesystem path for uploaded files (relative to UPLOAD_BASE_PATH)'),
    sa.Column('title', sa.String(length=512), nullable=True, comment='Article title (extracted or provided)'),
    sa.Column('extraction_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='extraction_status', create_constraint=True), server_default='pending', nullable=False, comment='Content extraction status'),
    sa.Column('content_text', sa.Text(), nullable=True, comment='Extracted text content'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When article was added'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When article was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (null = not deleted)'),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_deleted_at'), 'articles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_articles_extraction_status'), 'articles', ['extraction_status'], unique=False)
    op.create_index('ix_articles_session_deleted', 'articles', ['session_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_articles_session_id'), 'articles', ['session_id'], unique=False)
    op.create_index('ix_articles_session_status', 'articles', ['session_id', 'extraction_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_session_status', table_name='articles')
    op.drop_index(op.f('ix_articles_session_id'), table_name='articles')
    op.drop_index('ix_articles_session_deleted', table_name='articles')
    op.drop_index(op.f('ix_articles_extraction_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_deleted_at'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
