"""add research sessions table

Revision ID: f304b02c7230
Revises: 608494810fe8
Create Date: 2026-01-19 09:30:45.735389

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f304b02c7230"
down_revision: str | Sequence[str] | None = "608494810fe8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Session display name"),
        sa.Column("description", sa.Text(), nullable=True, comment="Optional session description"),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "active",
                "completed",
                "archived",
                name="session_status",
                create_constraint=True,
            ),
            server_default="draft",
            nullable=False,
            comment="Session lifecycle status",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When session was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When session was last updated",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Soft delete timestamp (null = not deleted)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_sessions_deleted_at"), "research_sessions", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_research_sessions_name"), "research_sessions", ["name"], unique=False)
    op.create_index(
        op.f("ix_research_sessions_status"), "research_sessions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_research_sessions_status"), table_name="research_sessions")
    op.drop_index(op.f("ix_research_sessions_name"), table_name="research_sessions")
    op.drop_index(op.f("ix_research_sessions_deleted_at"), table_name="research_sessions")
    op.drop_table("research_sessions")
    # ### end Alembic commands ###
